name: DMZ
version: 1
author: thamma
main: me.thamma.DMZ.core.Main
website: http://github.com/thamma/
commands:
    chest:
       description: Use /chest for help
       usage: /chest
    warp:
       description: Use /warp for help
       usage: /warp
    data:
       description: Use /data for help
       usage: /data
    chunky:
       description: Use /chunky for help
       usage: /chunky